---
# tasks file for perfsonar-docker

- name: check to see if we support the requested package
  fail:
    msg: "Unsupported package requested"
  when: perfsonar_docker_bundle != "tools" and
        perfsonar_docker_bundle != "testpoint"

- name: Toolkit Install
  import_tasks: tools.yml
  when: perfsonar_docker_bundle == "tools"

- name: Testpoint Install
  import_tasks: testpoint.yml
  when: perfsonar_docker_bundle == "testpoint"
